feat: deploy with predefined config through GH action (#469)
* Handle string type for numOfNodes context value.

Previously, the numOfNodes context value was assumed to be a float64, leading to potential conversion issues if it was provided as a string. Now, the code checks and properly converts the context value if it's a string, and logs an error if the conversion fails, ensuring more robust handling of context values.

* Remove GENESIS_PATH from environment variables

The GENESIS_PATH environment variable was redundant and unused. This change simplifies the configuration by removing unnecessary variables, making the codebase cleaner and easier to maintain.

* Add inputs and validations for deploy-auto workflow

Enhanced the deploy-auto workflow to allow specifying the number of nodes and subdomain through inputs. Added validation to restrict auto deployments to the 'dev' subdomain only, and ensured parameters are correctly passed and context values are set for deployment flexibility.

* Add NODE_PRIVATE_KEYS secret and refine CDK deploy command

Included NODE_PRIVATE_KEYS secret to the environment variables for deployment. Updated the CDK deploy command to target specific stacks and added a deployment stage context for more precise control. This ensures only necessary stacks are deployed and improves deployment security.

* Add RESTART_HASH docs to control TSN redeployments

* Add GitHub Actions deployment instructions to README

Document new deployment workflows for automated and staging environments using GitHub Actions. Includes setup inputs, AWS deployment details, and references to configuration files.

* Update deploy command to use TSN-From-Config stack

Updated the CDK deploy command in deploy-staging.yaml to target the newly renamed TSN-From-Config stack instead of the previous TSN-DB stack. This includes updating the stack names in the parameters and ensuring the deployment context is set to STAGING.

* Add error handling to genesis.json download in staging deploy

Updated the cURL command to include error handling parameters like `-f`, `--silent`, and `--show-error`. This ensures that any failure in downloading the genesis.json file will provide a clear error message.

* Add genesis file validation and fix deployment script

Added a `validateGenesisFile` function to check the existence and validity of the genesis file in `peer_config_gen.go`. Also, updated the deployment script in `deploy-staging.yaml` to ensure the correct path and parameters are used for the staging environment.

* Update error handling in config and peer config generation

Changed error logs to panic with detailed messages in the config and peer configuration files. This ensures immediate attention to critical issues by including specific file paths and error details in panic statements.

diff --git a/.github/workflows/deploy-staging.yaml b/.github/workflows/deploy-staging.yaml
--- a/.github/workflows/deploy-staging.yaml
+++ b/.github/workflows/deploy-staging.yaml
@@ -17,11 +17,13 @@ jobs:
           AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
           GW_SESSION_SECRET: ${{ secrets.GW_SESSION_SECRET }}
+          # NODE_PRIVATE_KEYS is a comma separated list of private keys of the nodes to act as validators
+          NODE_PRIVATE_KEYS: ${{ secrets.NODE_PRIVATE_KEYS }}
           # PRIVATE_KEY is the private key of the account that will be used to deploy the TSN system contract
           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
           # READ_TOKEN is the token used to read the genesis.json from the tsn-node-operator repo
           READ_TOKEN: ${{ secrets.READ_TOKEN }}
-        if: ${{ env.AWS_ACCESS_KEY == '' || env.AWS_SECRET_KEY == '' || env.GW_SESSION_SECRET == '' || env.PRIVATE_KEY == '' || env.READ_TOKEN == '' }}
+        if: ${{ env.AWS_ACCESS_KEY == '' || env.AWS_SECRET_KEY == '' || env.GW_SESSION_SECRET == '' || env.PRIVATE_KEY == '' || env.READ_TOKEN == '' || env.NODE_PRIVATE_KEYS == '' }}
         run: |
           echo "Missing secrets"
           exit 1
@@ -39,7 +41,11 @@ jobs:
 
       - name: Get updated genesis.json
         run: |
-          curl -H "Authorization: token ${{ secrets.READ_TOKEN }}" --create-dirs -o ./deployments/network/staging/genesis.json https://raw.githubusercontent.com/truflation/tsn-node-operator/main/configs/network/staging/genesis.json
+          curl -f -H "Authorization: token ${{ secrets.READ_TOKEN }}" \
+            --create-dirs -o ./deployments/network/staging/genesis.json \
+            https://raw.githubusercontent.com/truflation/tsn-node-operator/main/configs/network/staging/genesis.json \
+            --silent --show-error \
+            || echo "Error: Failed to download genesis.json (HTTP status code: $?)"
 
       - name: Setup Go
         uses: actions/setup-go@v5
@@ -84,16 +90,23 @@ jobs:
           cd deployments/infra
           # this must be on absolute path
           export CDK_DOCKER=$(pwd)/buildx.sh
+          
+          # transform to absolute path
+          export GENESIS_PATH=$(realpath ../network/staging/genesis.json)
+          # make sure there's a file there
+          ls -l $GENESIS_PATH
 
           # GW_CORS_ALLOW_ORIGINS = Comma separated list of allowed origins
-          cdk deploy --require-approval never --all \
-            --parameters TSN-DB-Stack:sessionSecret=${{ secrets.GW_SESSION_SECRET }} \
-            --parameters TSN-DB-Stack:corsAllowOrigins=${{ secrets.GW_CORS_ALLOW_ORIGINS || '*' }}
+          cdk deploy --require-approval never TSN-From-Config* TSN-Cert* \
+            --exclusively \
+            --parameters TSN-From-Config-dev-Stack:sessionSecret=${{ secrets.GW_SESSION_SECRET }} \
+            --parameters TSN-From-Config-dev-Stack:corsAllowOrigins=${{ secrets.GW_CORS_ALLOW_ORIGINS || '*' }} \
+            --context deploymentStage=DEV
 
         env:
           CI: true
           # used to instantiate configuration
           KWIL_ADMIN_BIN_PATH: ../../.build/kwil-admin
-          GENESIS_PATH: ../../deployments/network/genesis.json
           CHAIN_ID: truflation-staging
           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
+          NODE_PRIVATE_KEYS: ${{ secrets.NODE_PRIVATE_KEYS }}
